package com.RegressionTestSelectionTool.Technique;

public enum SelectionTechniqueEnum {
	CHANGE_BASED,
	CLASS_FIREWALL,
    SMELL_BASED,
    SMELL_FIREWALL,
    CHANGE_AND_SMELL_BASED,
    CHANGE_AND_SMELL_FIREWALL,
    CHANGE_AND_SMELL_INTERSECTION_BASED,
    CHANGE_AND_SMELL_INTERSECTION_FIREWALL
}
